services:
  frontend:
    container_name: frontend
    image: frontend:latest
    networks:
      - mern-net
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    image: backend:latest
    ports:
      - "3000:3000"
    container_name: backend
    networks:
      - mern-net
    volumes:
      - backend-data:/app/data

networks:
  mern-net:

volumes:
  frontend-data:
  backend-data:

