name: task2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ self-hosted, linux, x64 ]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: |
          docker build -t backend:1.0.0 ./backend
          docker build -t frontend:1.0.0 ./frontend

      - name: Stop existing stack
        run: docker-compose down || true

      - name: Start stack
        run: docker-compose up -d

      - name: Cleanup unused images
        run: docker image prune -f
